---

- name: upgrade all packages
  become: yes
  yum:
    name: '*'
    state: latest

- name: install pkgs
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

 


 































